name: Post welcome message
on: 
  pull_request: 
    types: [opened]
jobs:
  bulid:
    name: Post welcom comment
    runs-on: ubuntu-latest
    steps:
      - run: gh pr comment $PR_URL --body "Welcome to the repo"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          
    
